-- ⟨ψ⟩Quantum schema — extracted from src/utils/init_db.py
-- Regenerated by FR-20260423-sibling-gitignore-parity.
-- Source of truth: src/utils/init_db.py. Re-run `C:\G\python.exe src/utils/init_db.py`
-- to materialize an encrypted quantumpsi.db locally.

PRAGMA journal_mode=WAL;

CREATE TABLE IF NOT EXISTS benchmarks (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    algorithm       TEXT NOT NULL,
    total_time_sec  REAL NOT NULL,
    required_qubits INTEGER NOT NULL,
    n_value         INTEGER NOT NULL,
    order_r         INTEGER,
    factor1         INTEGER,
    factor2         INTEGER,
    backend         TEXT NOT NULL,
    timestamp       TEXT NOT NULL,
    created_at      TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_benchmarks_algorithm ON benchmarks(algorithm);
CREATE INDEX IF NOT EXISTS idx_benchmarks_backend ON benchmarks(backend);

CREATE TABLE IF NOT EXISTS benchmark_provenance (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id                   TEXT NOT NULL UNIQUE,
    identity_family          TEXT NOT NULL,
    manifest_version         TEXT NOT NULL,
    provenance_status        TEXT NOT NULL,
    manifest_json            TEXT NOT NULL,
    evidence_references_json TEXT NOT NULL,
    created_at               TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_benchmark_provenance_family
    ON benchmark_provenance(identity_family);

CREATE TABLE IF NOT EXISTS shor_replay_benchmarks (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id              TEXT NOT NULL,
    mode                TEXT NOT NULL CHECK(mode IN ('ideal', 'noisy', 'qpu')),
    n_value             INTEGER NOT NULL,
    repetitions         INTEGER NOT NULL,
    successes           INTEGER NOT NULL,
    success_rate        REAL NOT NULL,
    ci_95_low           REAL NOT NULL,
    ci_95_high          REAL NOT NULL,
    seed                INTEGER,
    order_summary_json  TEXT NOT NULL,
    provenance_json     TEXT NOT NULL,
    created_at          TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_shor_replay_run_mode
    ON shor_replay_benchmarks(run_id, mode);

-- Cache depletion guard health log (FR-20260524-quantum-cache-depletion-guard)
CREATE TABLE IF NOT EXISTS cache_health_log (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    ts              TEXT    NOT NULL,
    bits_remaining  INTEGER NOT NULL,
    capacity_bits   INTEGER NOT NULL,
    pct_full        REAL    NOT NULL,
    action_taken    TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_cache_health_log_ts ON cache_health_log(ts);

-- Batch job retry/backoff status (FR-20260704-qiskit-aer-retry-supervisor)
CREATE TABLE IF NOT EXISTS job_retry_status (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id       TEXT    NOT NULL UNIQUE,
    backend      TEXT    NOT NULL CHECK(backend IN ('aer', 'ibm')),
    status       TEXT    NOT NULL CHECK(status IN ('pending', 'running', 'succeeded', 'failed', 'retrying')),
    attempt      INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 3,
    error_msg    TEXT,
    created_at   TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at   TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_job_retry_status_job_id ON job_retry_status(job_id);

