-- ⟨ψ⟩Quantum schema — extracted from src/utils/init_db.py
-- Regenerated by FR-20260423-sibling-gitignore-parity.
-- Source of truth: src/utils/init_db.py. Re-run `C:\G\python.exe src/utils/init_db.py`
-- to materialize an encrypted quantumpsi.db locally.

PRAGMA journal_mode=WAL;

CREATE TABLE IF NOT EXISTS benchmarks (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    algorithm       TEXT NOT NULL,
    total_time_sec  REAL NOT NULL,
    required_qubits INTEGER NOT NULL,
    n_value         INTEGER NOT NULL,
    order_r         INTEGER,
    factor1         INTEGER,
    factor2         INTEGER,
    backend         TEXT NOT NULL,
    timestamp       TEXT NOT NULL,
    created_at      TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_benchmarks_algorithm ON benchmarks(algorithm);
CREATE INDEX IF NOT EXISTS idx_benchmarks_backend ON benchmarks(backend);
